name: Issue
on: issues
jobs:
    Test:
        name: issue
        runs-on: ubuntu-latest
        steps:
            - name: Output Event Details
              run: echo "${{ tojson(github.event) }}"
            