name: Issue
on: issues
jobs:
    Test:
        name: issue
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              run: echo "${{ tojson(github).event }}"
            